// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Artist struct {
	ID    int     `json:"id"`
	Name  string  `json:"name"`
	Songs []*Song `json:"songs"`
}

type NewArtist struct {
	Name string `json:"name"`
}

type NewSong struct {
	Name     string `json:"name"`
	ArtistID int    `json:"artistId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Song struct {
	ID       int     `json:"id"`
	Name     string  `json:"name"`
	ArtistID int     `json:"artistId"`
	Artist   *Artist `json:"artist"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
